### ISSUE TITLE
The over the daily limit mount was not blocked by the UI properly, and was locked in the smart contract

### ISSUE THREAD

**Issue by billyinscn** [PepperSecDev/thunder_bridge#16]
Repro steps:
1. Try to do DAI->TT-DAI conversation with over the daily limit amount (300K+1) from Ethereum side
2. After inputting DAI amount of 300,001 in the UI, and clicked "transfer", we observed the the 300,001 DAI was deducted from the koven wallet , but the corresponding TT-DAI was not show up in the thunder testnet wallet.
3. Please refer to the TX: https://kovan.etherscan.io/tx/0x4fb10129bf72201aa04b80dae80890499f982211478b869a8c1e302f11f32c6f

**Comment by pertsev** [comment]
`fixAssetsAboveLimits` resolves the issue
Have a look at the [source code](https://github.com/PepperSecDev/thunder_bridge/blob/e904bb7a54ffa08c44cc45e78cec62480b70fde6/contracts/contracts/upgradeable_contracts/OverdrawManagement.sol#L13-L24) and [tests](https://github.com/PepperSecDev/thunder_bridge/blob/e904bb7a54ffa08c44cc45e78cec62480b70fde6/contracts/test/erc_to_erc/home_bridge.test.js#L514)
